##############################################################################
# FILE: beamform.makefile
# DESCRIPTION:
#   Makefile for multi-threaded
###############################################################################
beamform_mt:
	@echo ">>> Making Multi-threaded version using Ofast flag >>>"
	gcc beamform_mt.c -o beamform_mt -lm -lpthread -Ofast

.PHONY: beamform_mt